language: ruby
rvm:
- 2.5.1
env:
  global:
  - secure: FMLm8th9arjF4KKy6TzkQLX3ForFJrDHFDmqMwsP5PQV3ml6NtLFimLbLpCotLbCpKQvb8pF/dLxySmH0KxXSTJ+RnbqR3ye2lE7C3TpvvjSPwq1dNZRm5BIIwU1f0youcYVVE2qG7jbEYJI19LRmFAs2wZCU+b6PXfbUVyHtqU=
  - secure: e+g5U7Fw3/AiK6OCt28tDpUKsIGUWSC3pbrmLeb/zgk4uPr6dAdpxeCyy/C+L8T4jtzkYfX6ahtJiVEoH1v72SOUwbPJxVehjyaNtP+ekq5YEUNTVxtysNZxMFs0HhrRhUko7kjdx2OB1u/F8ohUL1YX8UqceoN14gcSuqn/r2o=
deploy:
  provider: s3
  bucket: www.randrpump.com
  skip_cleanup: true
  region: us-east-1
  local_dir: build
notifications:
  slack:
    secure: d7qarAbbCWJO8Y3AoJGs/L60dO3BYUc/1q6ugDhM5Mpo2Kq0kv9orDeDlml6c1NsNNA1irLRiq9dyDsAsLM8NxqVZ+WB1B/CQFdHyjxH0fYmzEiMxH/imK8TafjefSBz9gz5+WtDO+tlRb2hsJmTbAwFbk4h3H3BEI9g50/VfI8=
